### ISSUE TITLE
any examples how to send binary data (with protobuf) ? 

### ISSUE THREAD

**Issue by snsg** [nats-io/stan.py#45]
having a hard time here finding out how to get away from text only data and instead be able to transmit binary data  ? can any one help me with an example of that, am only after like an ultra simple packet structure with ex an identifer+lenght+databuffer for example but dont really know how to get that working in python ?

**Comment by snsg** [comment]
not sure why i stared myself blind on things had to be text, can see i can just pass on a byte array with no problems :)

**Comment by wallyqs** [comment]
glad you got it to work!
