### ISSUE TITLE
ModuleNotFoundError: No module named 'nats.aio'

### ISSUE THREAD

**Issue by Ignacio-Vidal** [nats-io/stan.py#48]
Hi, could you look at the following error and help me to solve it?

When installing the "asyncio-nats-streaming" package and importing the clients as described in the stan.py file:
- from nats.aio.client import Client as NATS
- from stan.aio.client import Client as STAN

I get the following error:
- from nats.aio.client import Client as NATS -> ModuleNotFoundError: No module named 'nats.aio'

I am running a docker container with the "python:3.7" base image and this is my requirements.txt:
- fastapi==0.46.0
- uvicorn==0.11.2
- pandas==1.0.1
- numpy==1.18.1
- requests==2.22.0
- email-validator==1.0.5
- yfinance==0.1.54
- pytest===5.3.5
- redis==3.4.1
- asyncio-nats-streaming==0.3.0

I have even tried adding the "asyncio-nats-client==0.11.4"  to the requirements.txt and still get the same error when importing "from nats.aio.client import Client as NATS".

Thank you

**Comment by charliestrawn** [comment]
>I am running a docker container with the "python:3.7" base image and this is my requirements.txt

Just to sanity check have you pip installed the requirements in your Dockerfile/container? If you try to `import requests` in your python file do you see a module not found for that as well?

**Comment by alexander-krichmar** [comment]
Have the same error guys. Python 3.9, Windows 10

**Comment by wallyqs** [comment]
I think this happens when the name of the file is named `nats.py`?

**Comment by Ignacio-Vidal** [comment]
> I think this happens when the name of the file is named `nats.py` or `stan.py`?

Yes, creating local modules or files with the name "nats" causes import issues. Closing the ticket.
